### ISSUE TITLE
Blueberry secret doesn’t do anything

### ISSUE THREAD

**Issue by TheGamer1002** [lvandeve/etherealfarm#8]
![2FABFD82-85C3-4E33-8622-795D9C624084](https://user-images.githubusercontent.com/48131223/165962944-ebde0ff8-8adb-4831-a509-18d36ed8119a.jpeg)
That’s just about it.

**Comment by lvandeve** [comment]
It should do something: what it currently does it make the unlock blueberry upgrade visible immediately, rather than after growing a blackberry. So it allows to immediately unlock it and plant a blueberry, saving time to wait for the blackberry, if having enough starter seeds.

However, this made me realize that it's quite unclear that blackberry secret unlocks it, while blueberry secret does not. In a next version blueberry secret will also unlock!

**Comment by TheGamer1002** [comment]
Thanks, it works now!
